apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: dev-udn-primary
  namespace: dev
spec:
  topology: Layer3 
  layer3: 
    role: Primary 
    subnets: 
      - cidr: 10.150.0.0/16
        hostSubnet: 24