apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello-bar
  name: hello-bar
  namespace: udn-bar
spec:
  containers:
  - name: hello-openshift
    image: quay.io/openshift/origin-hello-openshift
    ports:
    - containerPort: 8888
    imagePullPolicy: IfNotPresent
